language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly